version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ga-portfolio
    environment:
      - DATABASE_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - ADMIN_USER
      - ADMIN_PASSWORD
    depends_on:
      - db
    networks:
      - webcloud

  db:
    image: postgres:15-alpine
    container_name: ga-portfolio-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webcloud

volumes:
  postgres_data:


networks:
  webcloud:
    external: true
